//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by XBT Client.rc
//
#define IDD_XBTCLIENT_DIALOG            102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_OPTIONS                     103
#define CG_IDR_POPUP_XBTCLIENT_DLG      104
#define IDR_POPUP_BOTTOM_FILES          105
#define IDR_POPUP_BOTTOM                106
#define IDR_MAINFRAME                   128
#define IDD_TORRENT                     132
#define IDD_FILES                       133
#define IDD_TRACKERS                    134
#define IDD_TRACKER                     135
#define IDD_ABOUT                       136
#define IDD_MAKE_TORRENT                137
#define IDD_TORRENT_OPTIONS             138
#define IDD_SCHEDULER                   139
#define IDD_PROFILES                    140
#define IDD_PROFILE                     141
#define IDD_SCHEDULER_ENTRY             142
#define IDR_TRAY                        144
#define IDD_PEER_CONNECT                146
#define IDD_BLOCK_LIST                  148
#define IDC_FILES                       1000
#define IDC_PEERS                       1002
#define IDC_ADMIN_PORT                  1002
#define IDC_PEER_PORT                   1003
#define IDC_ALERTS                      1004
#define IDC_UPLOAD_RATE                 1004
#define IDC_PEER_LIMIT                  1007
#define IDC_TORRENT_LIMIT               1008
#define IDC_PUBLIC_IPA                  1010
#define IDC_UPLOAD_SLOTS                1012
#define IDC_DECREASE_PRIORITY           1013
#define IDC_SEEDING_RATIO               1013
#define IDC_INCREASE_PRIORITY           1014
#define IDC_LIST                        1014
#define IDC_FILES_LOCATION              1014
#define IDC_COMPLETES_DIRECTORY         1014
#define IDC_SEEDING_RATIO2              1014
#define IDC_MIN_UPLOAD_SLOTS            1014
#define IDC_UPLOAD_SLOTS_MIN            1014
#define IDC_INSERT                      1015
#define IDC_OPEN                        1015
#define IDC_INCOMPLETES_DIRECTORY       1015
#define IDC_SEEDING_RATIO3              1015
#define IDC_MAX_UPLOAD_SLOTS            1015
#define IDC_UPLOAD_SLOTS_MAX            1015
#define IDC_DELETE                      1016
#define IDC_EXPLORE                     1016
#define IDC_TORRENTS_DIRECTORY          1016
#define IDC_TRACKER                     1017
#define IDC_EDIT                        1017
#define IDC_USER                        1018
#define IDC_ACTIVATE                    1018
#define IDC_PASS                        1019
#define IDC_TRACKER_STATIC              1020
#define IDC_USER_STATIC                 1021
#define IDC_PASS_STATIC                 1022
#define IDC_SHOW_TRAY_ICON              1023
#define IDC_ASK_FOR_LOCATION            1025
#define IDC_SITE                        1026
#define IDC_START_MINIMIZED             1027
#define IDC_SAVE                        1030
#define IDC_NAME_STATIC                 1031
#define IDC_NAME                        1032
#define IDC_USE_MERKLE                  1033
#define IDC_TRACKERS                    1034
#define IDC_TRACKERS_STATIC             1035
#define IDC_END_MODE                    1036
#define IDC_LOWER_PROCESS_PRIORITY      1037
#define IDC_LICENSE                     1038
#define IDC_SEED_AFTER_MAKING           1039
#define IDC_LOAD_TRACKERS               1040
#define IDC_BIND_BEFORE_CONNECT         1041
#define IDC_EXCLUDE                     1042
#define IDC_COMPLETES_DIRECTORY_BROWSE  1043
#define IDC_INCOMPLETES_DIRECTORY_BROWSE 1044
#define IDC_TORRENTS_DIRECTORY_BROWSE   1045
#define IDC_SEEDING_RATIO_OVERRIDE      1047
#define IDC_SEEDING_RATIO_ENABLE        1049
#define IDC_UPLOAD_RATE_ENABLE          1050
#define IDC_UPLOAD_SLOTS_ENABLE         1051
#define IDC_PEER_LIMIT_ENABLE           1052
#define IDC_TORRENT_LIMIT_ENABLE        1053
#define IDC_TIME_STATIC                 1058
#define IDC_PROFILE_STATIC              1059
#define IDC_PROFILE                     1060
#define IDC_MINUTES                     1061
#define IDC_HOURS                       1062
#define IDC_SHOW_CONFIRM_EXIT_DIALOG    1062
#define IDC_SECONDS                     1063
#define IDC_HIDE_ON_DEACTIVATE          1063
#define IDC_MIN_UPLOAD_SLOTS_OVERRIDE   1064
#define IDC_UPLOAD_SLOTS_MIN_OVERRIDE   1064
#define IDC_SEND_STOP_EVENT             1064
#define IDC_MAX_UPLOAD_SLOTS_OVERRIDE   1065
#define IDC_UPLOAD_SLOTS_MAX_OVERRIDE   1065
#define IDC_UPNP                        1065
#define IDC_TAB                         1066
#define IDC_VERSION                     1068
#define IDC_HOTKEY1                     1069
#define IDC_HOT_KEY                     1069
#define IDC_ADMIN_PORT_STATIC           1070
#define IDC_PEER_PORT_STATIC            1071
#define IDC_PUBLIC_IPA_STATIC           1072
#define IDC_UPLOAD_RATE_STATIC          1073
#define IDC_UPLOAD_SLOTS_STATIC         1074
#define IDC_SEEDING_RATIO_STATIC        1075
#define IDC_COMPLETES_DIRECTORY_STATIC  1076
#define IDC_INCOMPLETES_DIRECTORY_STATIC 1077
#define IDC_TORRENTS_DIRECTORY_STATIC   1078
#define IDC_PEER_LIMIT_STATIC           1080
#define IDC_TORRENT_LIMIT_STATIC        1081
#define IDC_HOT_KEY_STATIC              1082
#define IDC_USER_AGENT_STATIC           1083
#define IDC_USER_AGENT                  1084
#define IDC_PEER_ID                     1085
#define IDC_HOST_STATIC                 1086
#define IDC_PORT_STATIC                 1087
#define IDC_PEER_ID_STATIC              1087
#define IDC_HOST                        1088
#define IDC_PORT                        1089
#define IDC_PRIORITY                    1089
#define IDC_PRIORITY_STATIC             1090
#define ID_POPUP_EXPLORE                32775
#define ID_POPUP_START                  32776
#define ID_POPUP_STOP                   32777
#define ID_POPUP_COPY                   32778
#define ID_POPUP_PASTE                  32779
#define ID_POPUP_FILES                  32780
#define ID_POPUP_ANNOUNCE               32782
#define ID_POPUP_EXPLORE_TRACKER        32783
#define ID_POPUP_TORRENT_OPTIONS        32787
#define ID_POPUP_TORRENT_CLIPBOARD_COPY_HASH 32790
#define ID_POPUP_TORRENT_CLIPBOARD_COPY_ANNOUNCE_URL 32791
#define ID_POPUP_VIEW_FILES             32794
#define ID_POPUP_VIEW_PEERS             32795
#define ID_POPUP_VIEW_TRACKERS          32796
#define ID_POPUP_VIEW_DETAILS           32797
#define ID_POPUP_VIEW_EVENTS            32798
#define ID_POPUP_PRIORITY_HIGH          32800
#define ID_POPUP_PRIORITY_NORMAL        32801
#define ID_POPUP_PRIORITY_LOW           32802
#define ID_POPUP_PRIORITY_EXCLUDE       32803
#define ID_POPUP_VIEW_TRAY_ICON         32805
#define ID_POPUP_UPLOAD_RATE_LIMIT      32806
#define ID_POPUP_TORRENT_PRIORITY_HIGH  32807
#define ID_POPUP_TORRENT_PRIORITY_NORMAL 32808
#define ID_POPUP_TORRENT_PRIORITY_LOW   32809
#define ID_POPUP_VIEW_PIECES            32810
#define ID_POPUP_TORRENT_PAUSE          32811
#define ID_POPUP_TORRENT_UNPAUSE        32812
#define ID_POPUP_TORRENT_QUEUE          32813
#define ID_POPUP_STATE_QUEUED           32814
#define ID_POPUP_STATE_STARTED          32815
#define ID_POPUP_STATE_PAUSED           32816
#define ID_POPUP_STATE_STOPPED          32817
#define ID_HELP_ABOUT                   32822
#define ID_FILE_EXIT                    32823
#define ID_EDIT_COPY_ANNOUNCE_URL       32824
#define ID_EDIT_COPY_HASH               32825
#define ID_EDIT_COPY_URL                32826
#define ID_EDIT_PASTE_URL               32827
#define ID_TOOLS_OPTIONS                32830
#define ID_TOOLS_SCHEDULER              32831
#define ID_TOOLS_TRACKERS               32832
#define ID_TOOLS_PROFILES               32834
#define ID_FILE_DELETE                  32835
#define ID_HELP_HOME_PAGE               32836
#define ID_POPUP_VIEW_GLOBAL_EVENTS     32838
#define ID_POPUP_VIEW_GLOBAL_DETAILS    32839
#define ID_POPUP_DISCONNECT             32840
#define ID_POPUP_CONNECT                32841
#define ID_EDIT_COPY_HOST               32842
#define ID_EDIT_COPY_ROWS               32843
#define ID_POPUP_BLOCK                  32845
#define ID_TOOLS_BLOCK_LIST             32846
#define ID_POPUP_PAUSED                 32848

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32849
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
